#!/bin/bash

# Docker setup script for PYHABOT
# This script creates the .env.docker file with proper user ID mapping

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "🐳 Setting up Docker environment for PYHABOT..."

# Get current user info
CURRENT_USER=$(id -un)
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)

echo "Current user: $CURRENT_USER (UID: $CURRENT_UID, GID: $CURRENT_GID)"

# Create .env.docker file
ENV_FILE="$PROJECT_DIR/.env.docker"
cat > "$ENV_FILE" << EOF
# Docker environment variables
# Auto-generated by setup-docker.sh
USER_ID=$CURRENT_UID
GROUP_ID=$CURRENT_GID

# Other configuration
TZ=Europe/Budapest
LOG_LEVEL=INFO
PERSISTENT_DATA_PATH=/data
EOF

echo "✅ Created $ENV_FILE with user ID mapping"

# Set proper ownership on persistent_data directory
DATA_DIR="$PROJECT_DIR/persistent_data"
if [ -d "$DATA_DIR" ]; then
    echo "📁 Setting ownership on persistent_data directory..."
    sudo chown -R "$CURRENT_USER:$CURRENT_USER" "$DATA_DIR"
    echo "✅ Permissions set on $DATA_DIR"
else
    echo "📁 Creating persistent_data directory..."
    mkdir -p "$DATA_DIR"
fi

echo ""
echo "🎉 Docker setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Build and start: docker compose --env-file .env.docker up --build -d pyhabot"
echo "2. View logs: docker compose --env-file .env.docker logs -f pyhabot"
echo "3. Execute commands: docker compose --env-file .env.docker exec pyhabot pyhabot list"
echo "4. Stop: docker compose --env-file .env.docker down"
echo ""
echo "💡 No more permission issues between local and Docker usage!"